class RegisterUserLocator():
    firstName = ('id' , 'customer.firstName')
    lastName = ('id' , 'customer.lastName')
    address = ('id' , 'customer.address.street')
    city = ('id' , 'customer.address.city')
    state = ('id' , 'customer.address.state')
    zipcode = ('id' , 'customer.address.zipCode')
    phone = ('id' , 'customer.phoneNumber')
    ssn = ('id' , 'customer.ssn')
    username = ('id' , 'customer.username')
    password = ('id' , 'customer.password')
    cnfrmPassword = ('id' , 'repeatedPassword')
    registerUser = ('xpath' , "//input[@value='Register']")
    verifyRegistration = ('xpath' , "//a[text()='Log Out']")